version: '2'

services:

  elasticsearch:
    image: 192.168.1.45:5000/vqcomms/elasticsearch
    ports:
      - 9200:9200
    environment:
      - ELASTIC_PASSWORD:MagicWord
  
  kibana:
    image: 192.168.1.45:5000/vqcomms/kibana
    ports:
      - 5601:5601
    environment:
      - ELASTIC_PASSWORD:MagicWord
    depends_on:
      - elasticsearch

    
